<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:tns="http://tempuri.org/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <s:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/">
      <s:element name="Login">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="username" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="password" type="s:string" />
            <s:element minOccurs="1" maxOccurs="1" name="Choice" type="s:boolean" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="LoginResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="LoginResult">
              <s:complexType>
                <s:sequence>
                  <s:any minOccurs="0" maxOccurs="unbounded" namespace="http://www.w3.org/2001/XMLSchema" processContents="lax" />
                  <s:any minOccurs="1" namespace="urn:schemas-microsoft-com:xml-diffgram-v1" processContents="lax" />
                </s:sequence>
              </s:complexType>
            </s:element>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="Regi">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="users" type="tns:Users" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="Users">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="UserN" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="Pass" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="NameF" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="LastN" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="Fulladdres" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="Email" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="Pic" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="Gender" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="Birthday" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="PhoneN" type="s:string" />
        </s:sequence>
      </s:complexType>
      <s:element name="RegiResponse">
        <s:complexType />
      </s:element>
      <s:element name="UpdateUser">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="user" type="tns:Users" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="UpdateUserResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="UpdateUserResult">
              <s:complexType>
                <s:sequence>
                  <s:any minOccurs="0" maxOccurs="unbounded" namespace="http://www.w3.org/2001/XMLSchema" processContents="lax" />
                  <s:any minOccurs="1" namespace="urn:schemas-microsoft-com:xml-diffgram-v1" processContents="lax" />
                </s:sequence>
              </s:complexType>
            </s:element>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="SearchUser">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="data" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="option" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="SearchUserResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="SearchUserResult">
              <s:complexType>
                <s:sequence>
                  <s:any minOccurs="0" maxOccurs="unbounded" namespace="http://www.w3.org/2001/XMLSchema" processContents="lax" />
                  <s:any minOccurs="1" namespace="urn:schemas-microsoft-com:xml-diffgram-v1" processContents="lax" />
                </s:sequence>
              </s:complexType>
            </s:element>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="CreateMoviesTable">
        <s:complexType />
      </s:element>
      <s:element name="CreateMoviesTableResponse">
        <s:complexType />
      </s:element>
      <s:element name="GetAllMovies">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="year" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="GetAllMoviesResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="GetAllMoviesResult">
              <s:complexType>
                <s:sequence>
                  <s:any minOccurs="0" maxOccurs="unbounded" namespace="http://www.w3.org/2001/XMLSchema" processContents="lax" />
                  <s:any minOccurs="1" namespace="urn:schemas-microsoft-com:xml-diffgram-v1" processContents="lax" />
                </s:sequence>
              </s:complexType>
            </s:element>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="GetLatestMovies">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="movieid" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="GetLatestMoviesResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="GetLatestMoviesResult">
              <s:complexType>
                <s:sequence>
                  <s:any minOccurs="0" maxOccurs="unbounded" namespace="http://www.w3.org/2001/XMLSchema" processContents="lax" />
                  <s:any minOccurs="1" namespace="urn:schemas-microsoft-com:xml-diffgram-v1" processContents="lax" />
                </s:sequence>
              </s:complexType>
            </s:element>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="SearchMovies">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="data" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="option" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="SearchMoviesResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="SearchMoviesResult">
              <s:complexType>
                <s:sequence>
                  <s:any minOccurs="0" maxOccurs="unbounded" namespace="http://www.w3.org/2001/XMLSchema" processContents="lax" />
                  <s:any minOccurs="1" namespace="urn:schemas-microsoft-com:xml-diffgram-v1" processContents="lax" />
                </s:sequence>
              </s:complexType>
            </s:element>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="GetWishlistMovies">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="username" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="GetWishlistMoviesResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="GetWishlistMoviesResult">
              <s:complexType>
                <s:sequence>
                  <s:any minOccurs="0" maxOccurs="unbounded" namespace="http://www.w3.org/2001/XMLSchema" processContents="lax" />
                  <s:any minOccurs="1" namespace="urn:schemas-microsoft-com:xml-diffgram-v1" processContents="lax" />
                </s:sequence>
              </s:complexType>
            </s:element>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="AddToWishlist">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="username" type="s:string" />
            <s:element minOccurs="1" maxOccurs="1" name="movieId" type="s:int" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="AddToWishlistResponse">
        <s:complexType />
      </s:element>
      <s:element name="RemoveFromWishlist">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="username" type="s:string" />
            <s:element minOccurs="1" maxOccurs="1" name="movieId" type="s:int" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="RemoveFromWishlistResponse">
        <s:complexType />
      </s:element>
      <s:element name="AddWishListMovies">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="username" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="careCode" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="AddWishListMoviesResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="AddWishListMoviesResult" type="s:boolean" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="AddMovieComment">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="username" type="s:string" />
            <s:element minOccurs="1" maxOccurs="1" name="movieId" type="s:int" />
            <s:element minOccurs="1" maxOccurs="1" name="rating" type="s:int" />
            <s:element minOccurs="0" maxOccurs="1" name="commentText" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="AddMovieCommentResponse">
        <s:complexType />
      </s:element>
      <s:element name="GetMovieComments">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="movieId" type="s:int" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="GetMovieCommentsResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="GetMovieCommentsResult">
              <s:complexType>
                <s:sequence>
                  <s:any minOccurs="0" maxOccurs="unbounded" namespace="http://www.w3.org/2001/XMLSchema" processContents="lax" />
                  <s:any minOccurs="1" namespace="urn:schemas-microsoft-com:xml-diffgram-v1" processContents="lax" />
                </s:sequence>
              </s:complexType>
            </s:element>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="CreateCelebsTable">
        <s:complexType />
      </s:element>
      <s:element name="CreateCelebsTableResponse">
        <s:complexType />
      </s:element>
      <s:element name="GetAllCelebs">
        <s:complexType />
      </s:element>
      <s:element name="GetAllCelebsResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="GetAllCelebsResult">
              <s:complexType>
                <s:sequence>
                  <s:any minOccurs="0" maxOccurs="unbounded" namespace="http://www.w3.org/2001/XMLSchema" processContents="lax" />
                  <s:any minOccurs="1" namespace="urn:schemas-microsoft-com:xml-diffgram-v1" processContents="lax" />
                </s:sequence>
              </s:complexType>
            </s:element>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="GetLatestCelebs">
        <s:complexType />
      </s:element>
      <s:element name="GetLatestCelebsResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="GetLatestCelebsResult">
              <s:complexType>
                <s:sequence>
                  <s:any minOccurs="0" maxOccurs="unbounded" namespace="http://www.w3.org/2001/XMLSchema" processContents="lax" />
                  <s:any minOccurs="1" namespace="urn:schemas-microsoft-com:xml-diffgram-v1" processContents="lax" />
                </s:sequence>
              </s:complexType>
            </s:element>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="SearchCelebs">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="data" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="option" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="SearchCelebsResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="SearchCelebsResult">
              <s:complexType>
                <s:sequence>
                  <s:any minOccurs="0" maxOccurs="unbounded" namespace="http://www.w3.org/2001/XMLSchema" processContents="lax" />
                  <s:any minOccurs="1" namespace="urn:schemas-microsoft-com:xml-diffgram-v1" processContents="lax" />
                </s:sequence>
              </s:complexType>
            </s:element>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="AddCeleb">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="celeb" type="tns:Celeb" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="Celeb">
        <s:sequence>
          <s:element minOccurs="1" maxOccurs="1" name="CelebId" type="s:int" />
          <s:element minOccurs="0" maxOccurs="1" name="Name" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="Role" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="Photo" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="Bio" type="s:string" />
        </s:sequence>
      </s:complexType>
      <s:element name="AddCelebResponse">
        <s:complexType />
      </s:element>
      <s:element name="UpdateCeleb">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="celeb" type="tns:Celeb" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="UpdateCelebResponse">
        <s:complexType />
      </s:element>
      <s:element name="DeleteCeleb">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="celebId" type="s:int" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="DeleteCelebResponse">
        <s:complexType />
      </s:element>
      <s:element name="GetMovies">
        <s:complexType />
      </s:element>
      <s:element name="GetMoviesResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="GetMoviesResult">
              <s:complexType>
                <s:sequence>
                  <s:any minOccurs="0" maxOccurs="unbounded" namespace="http://www.w3.org/2001/XMLSchema" processContents="lax" />
                  <s:any minOccurs="1" namespace="urn:schemas-microsoft-com:xml-diffgram-v1" processContents="lax" />
                </s:sequence>
              </s:complexType>
            </s:element>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="AddWishlist">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="username" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="product" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="AddWishlistResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="AddWishlistResult" type="s:boolean" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="RemoveWishlist">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="username" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="product" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="RemoveWishlistResponse">
        <s:complexType />
      </s:element>
      <s:element name="RemoveFromWishList">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="username" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="product" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="RemoveFromWishListResponse">
        <s:complexType />
      </s:element>
      <s:element name="AddToCart">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="username" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="code_prod" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="qua" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="price" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="AddToCartResponse">
        <s:complexType />
      </s:element>
    </s:schema>
  </wsdl:types>
  <wsdl:message name="LoginSoapIn">
    <wsdl:part name="parameters" element="tns:Login" />
  </wsdl:message>
  <wsdl:message name="LoginSoapOut">
    <wsdl:part name="parameters" element="tns:LoginResponse" />
  </wsdl:message>
  <wsdl:message name="RegiSoapIn">
    <wsdl:part name="parameters" element="tns:Regi" />
  </wsdl:message>
  <wsdl:message name="RegiSoapOut">
    <wsdl:part name="parameters" element="tns:RegiResponse" />
  </wsdl:message>
  <wsdl:message name="UpdateUserSoapIn">
    <wsdl:part name="parameters" element="tns:UpdateUser" />
  </wsdl:message>
  <wsdl:message name="UpdateUserSoapOut">
    <wsdl:part name="parameters" element="tns:UpdateUserResponse" />
  </wsdl:message>
  <wsdl:message name="SearchUserSoapIn">
    <wsdl:part name="parameters" element="tns:SearchUser" />
  </wsdl:message>
  <wsdl:message name="SearchUserSoapOut">
    <wsdl:part name="parameters" element="tns:SearchUserResponse" />
  </wsdl:message>
  <wsdl:message name="CreateMoviesTableSoapIn">
    <wsdl:part name="parameters" element="tns:CreateMoviesTable" />
  </wsdl:message>
  <wsdl:message name="CreateMoviesTableSoapOut">
    <wsdl:part name="parameters" element="tns:CreateMoviesTableResponse" />
  </wsdl:message>
  <wsdl:message name="GetAllMoviesSoapIn">
    <wsdl:part name="parameters" element="tns:GetAllMovies" />
  </wsdl:message>
  <wsdl:message name="GetAllMoviesSoapOut">
    <wsdl:part name="parameters" element="tns:GetAllMoviesResponse" />
  </wsdl:message>
  <wsdl:message name="GetLatestMoviesSoapIn">
    <wsdl:part name="parameters" element="tns:GetLatestMovies" />
  </wsdl:message>
  <wsdl:message name="GetLatestMoviesSoapOut">
    <wsdl:part name="parameters" element="tns:GetLatestMoviesResponse" />
  </wsdl:message>
  <wsdl:message name="SearchMoviesSoapIn">
    <wsdl:part name="parameters" element="tns:SearchMovies" />
  </wsdl:message>
  <wsdl:message name="SearchMoviesSoapOut">
    <wsdl:part name="parameters" element="tns:SearchMoviesResponse" />
  </wsdl:message>
  <wsdl:message name="GetWishlistMoviesSoapIn">
    <wsdl:part name="parameters" element="tns:GetWishlistMovies" />
  </wsdl:message>
  <wsdl:message name="GetWishlistMoviesSoapOut">
    <wsdl:part name="parameters" element="tns:GetWishlistMoviesResponse" />
  </wsdl:message>
  <wsdl:message name="AddToWishlistSoapIn">
    <wsdl:part name="parameters" element="tns:AddToWishlist" />
  </wsdl:message>
  <wsdl:message name="AddToWishlistSoapOut">
    <wsdl:part name="parameters" element="tns:AddToWishlistResponse" />
  </wsdl:message>
  <wsdl:message name="RemoveFromWishlistSoapIn">
    <wsdl:part name="parameters" element="tns:RemoveFromWishlist" />
  </wsdl:message>
  <wsdl:message name="RemoveFromWishlistSoapOut">
    <wsdl:part name="parameters" element="tns:RemoveFromWishlistResponse" />
  </wsdl:message>
  <wsdl:message name="AddWishListMoviesSoapIn">
    <wsdl:part name="parameters" element="tns:AddWishListMovies" />
  </wsdl:message>
  <wsdl:message name="AddWishListMoviesSoapOut">
    <wsdl:part name="parameters" element="tns:AddWishListMoviesResponse" />
  </wsdl:message>
  <wsdl:message name="AddMovieCommentSoapIn">
    <wsdl:part name="parameters" element="tns:AddMovieComment" />
  </wsdl:message>
  <wsdl:message name="AddMovieCommentSoapOut">
    <wsdl:part name="parameters" element="tns:AddMovieCommentResponse" />
  </wsdl:message>
  <wsdl:message name="GetMovieCommentsSoapIn">
    <wsdl:part name="parameters" element="tns:GetMovieComments" />
  </wsdl:message>
  <wsdl:message name="GetMovieCommentsSoapOut">
    <wsdl:part name="parameters" element="tns:GetMovieCommentsResponse" />
  </wsdl:message>
  <wsdl:message name="CreateCelebsTableSoapIn">
    <wsdl:part name="parameters" element="tns:CreateCelebsTable" />
  </wsdl:message>
  <wsdl:message name="CreateCelebsTableSoapOut">
    <wsdl:part name="parameters" element="tns:CreateCelebsTableResponse" />
  </wsdl:message>
  <wsdl:message name="GetAllCelebsSoapIn">
    <wsdl:part name="parameters" element="tns:GetAllCelebs" />
  </wsdl:message>
  <wsdl:message name="GetAllCelebsSoapOut">
    <wsdl:part name="parameters" element="tns:GetAllCelebsResponse" />
  </wsdl:message>
  <wsdl:message name="GetLatestCelebsSoapIn">
    <wsdl:part name="parameters" element="tns:GetLatestCelebs" />
  </wsdl:message>
  <wsdl:message name="GetLatestCelebsSoapOut">
    <wsdl:part name="parameters" element="tns:GetLatestCelebsResponse" />
  </wsdl:message>
  <wsdl:message name="SearchCelebsSoapIn">
    <wsdl:part name="parameters" element="tns:SearchCelebs" />
  </wsdl:message>
  <wsdl:message name="SearchCelebsSoapOut">
    <wsdl:part name="parameters" element="tns:SearchCelebsResponse" />
  </wsdl:message>
  <wsdl:message name="AddCelebSoapIn">
    <wsdl:part name="parameters" element="tns:AddCeleb" />
  </wsdl:message>
  <wsdl:message name="AddCelebSoapOut">
    <wsdl:part name="parameters" element="tns:AddCelebResponse" />
  </wsdl:message>
  <wsdl:message name="UpdateCelebSoapIn">
    <wsdl:part name="parameters" element="tns:UpdateCeleb" />
  </wsdl:message>
  <wsdl:message name="UpdateCelebSoapOut">
    <wsdl:part name="parameters" element="tns:UpdateCelebResponse" />
  </wsdl:message>
  <wsdl:message name="DeleteCelebSoapIn">
    <wsdl:part name="parameters" element="tns:DeleteCeleb" />
  </wsdl:message>
  <wsdl:message name="DeleteCelebSoapOut">
    <wsdl:part name="parameters" element="tns:DeleteCelebResponse" />
  </wsdl:message>
  <wsdl:message name="GetMoviesSoapIn">
    <wsdl:part name="parameters" element="tns:GetMovies" />
  </wsdl:message>
  <wsdl:message name="GetMoviesSoapOut">
    <wsdl:part name="parameters" element="tns:GetMoviesResponse" />
  </wsdl:message>
  <wsdl:message name="AddWishlistSoapIn">
    <wsdl:part name="parameters" element="tns:AddWishlist" />
  </wsdl:message>
  <wsdl:message name="AddWishlistSoapOut">
    <wsdl:part name="parameters" element="tns:AddWishlistResponse" />
  </wsdl:message>
  <wsdl:message name="RemoveWishlistSoapIn">
    <wsdl:part name="parameters" element="tns:RemoveWishlist" />
  </wsdl:message>
  <wsdl:message name="RemoveWishlistSoapOut">
    <wsdl:part name="parameters" element="tns:RemoveWishlistResponse" />
  </wsdl:message>
  <wsdl:message name="RemoveFromWishListSoapIn">
    <wsdl:part name="parameters" element="tns:RemoveFromWishList" />
  </wsdl:message>
  <wsdl:message name="RemoveFromWishListSoapOut">
    <wsdl:part name="parameters" element="tns:RemoveFromWishListResponse" />
  </wsdl:message>
  <wsdl:message name="AddToCartSoapIn">
    <wsdl:part name="parameters" element="tns:AddToCart" />
  </wsdl:message>
  <wsdl:message name="AddToCartSoapOut">
    <wsdl:part name="parameters" element="tns:AddToCartResponse" />
  </wsdl:message>
  <wsdl:portType name="ServiceSoap">
    <wsdl:operation name="Login">
      <wsdl:input message="tns:LoginSoapIn" />
      <wsdl:output message="tns:LoginSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="Regi">
      <wsdl:input message="tns:RegiSoapIn" />
      <wsdl:output message="tns:RegiSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="UpdateUser">
      <wsdl:input message="tns:UpdateUserSoapIn" />
      <wsdl:output message="tns:UpdateUserSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="SearchUser">
      <wsdl:input message="tns:SearchUserSoapIn" />
      <wsdl:output message="tns:SearchUserSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="CreateMoviesTable">
      <wsdl:input message="tns:CreateMoviesTableSoapIn" />
      <wsdl:output message="tns:CreateMoviesTableSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="GetAllMovies">
      <wsdl:input message="tns:GetAllMoviesSoapIn" />
      <wsdl:output message="tns:GetAllMoviesSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="GetLatestMovies">
      <wsdl:input message="tns:GetLatestMoviesSoapIn" />
      <wsdl:output message="tns:GetLatestMoviesSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="SearchMovies">
      <wsdl:input message="tns:SearchMoviesSoapIn" />
      <wsdl:output message="tns:SearchMoviesSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="GetWishlistMovies">
      <wsdl:input message="tns:GetWishlistMoviesSoapIn" />
      <wsdl:output message="tns:GetWishlistMoviesSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="AddToWishlist">
      <wsdl:input message="tns:AddToWishlistSoapIn" />
      <wsdl:output message="tns:AddToWishlistSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="RemoveFromWishlist">
      <wsdl:input message="tns:RemoveFromWishlistSoapIn" />
      <wsdl:output message="tns:RemoveFromWishlistSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="AddWishListMovies">
      <wsdl:input message="tns:AddWishListMoviesSoapIn" />
      <wsdl:output message="tns:AddWishListMoviesSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="AddMovieComment">
      <wsdl:input message="tns:AddMovieCommentSoapIn" />
      <wsdl:output message="tns:AddMovieCommentSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="GetMovieComments">
      <wsdl:input message="tns:GetMovieCommentsSoapIn" />
      <wsdl:output message="tns:GetMovieCommentsSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="CreateCelebsTable">
      <wsdl:input message="tns:CreateCelebsTableSoapIn" />
      <wsdl:output message="tns:CreateCelebsTableSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="GetAllCelebs">
      <wsdl:input message="tns:GetAllCelebsSoapIn" />
      <wsdl:output message="tns:GetAllCelebsSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="GetLatestCelebs">
      <wsdl:input message="tns:GetLatestCelebsSoapIn" />
      <wsdl:output message="tns:GetLatestCelebsSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="SearchCelebs">
      <wsdl:input message="tns:SearchCelebsSoapIn" />
      <wsdl:output message="tns:SearchCelebsSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="AddCeleb">
      <wsdl:input message="tns:AddCelebSoapIn" />
      <wsdl:output message="tns:AddCelebSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="UpdateCeleb">
      <wsdl:input message="tns:UpdateCelebSoapIn" />
      <wsdl:output message="tns:UpdateCelebSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="DeleteCeleb">
      <wsdl:input message="tns:DeleteCelebSoapIn" />
      <wsdl:output message="tns:DeleteCelebSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="GetMovies">
      <wsdl:input message="tns:GetMoviesSoapIn" />
      <wsdl:output message="tns:GetMoviesSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="AddWishlist">
      <wsdl:input message="tns:AddWishlistSoapIn" />
      <wsdl:output message="tns:AddWishlistSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="RemoveWishlist">
      <wsdl:input message="tns:RemoveWishlistSoapIn" />
      <wsdl:output message="tns:RemoveWishlistSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="RemoveFromWishList">
      <wsdl:input message="tns:RemoveFromWishListSoapIn" />
      <wsdl:output message="tns:RemoveFromWishListSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="AddToCart">
      <wsdl:input message="tns:AddToCartSoapIn" />
      <wsdl:output message="tns:AddToCartSoapOut" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ServiceSoap" type="tns:ServiceSoap">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="Login">
      <soap:operation soapAction="http://tempuri.org/Login" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Regi">
      <soap:operation soapAction="http://tempuri.org/Regi" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="UpdateUser">
      <soap:operation soapAction="http://tempuri.org/UpdateUser" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SearchUser">
      <soap:operation soapAction="http://tempuri.org/SearchUser" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CreateMoviesTable">
      <soap:operation soapAction="http://tempuri.org/CreateMoviesTable" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetAllMovies">
      <soap:operation soapAction="http://tempuri.org/GetAllMovies" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetLatestMovies">
      <soap:operation soapAction="http://tempuri.org/GetLatestMovies" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SearchMovies">
      <soap:operation soapAction="http://tempuri.org/SearchMovies" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetWishlistMovies">
      <soap:operation soapAction="http://tempuri.org/GetWishlistMovies" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AddToWishlist">
      <soap:operation soapAction="http://tempuri.org/AddToWishlist" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RemoveFromWishlist">
      <soap:operation soapAction="http://tempuri.org/RemoveFromWishlist" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AddWishListMovies">
      <soap:operation soapAction="http://tempuri.org/AddWishListMovies" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AddMovieComment">
      <soap:operation soapAction="http://tempuri.org/AddMovieComment" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetMovieComments">
      <soap:operation soapAction="http://tempuri.org/GetMovieComments" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CreateCelebsTable">
      <soap:operation soapAction="http://tempuri.org/CreateCelebsTable" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetAllCelebs">
      <soap:operation soapAction="http://tempuri.org/GetAllCelebs" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetLatestCelebs">
      <soap:operation soapAction="http://tempuri.org/GetLatestCelebs" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SearchCelebs">
      <soap:operation soapAction="http://tempuri.org/SearchCelebs" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AddCeleb">
      <soap:operation soapAction="http://tempuri.org/AddCeleb" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="UpdateCeleb">
      <soap:operation soapAction="http://tempuri.org/UpdateCeleb" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="DeleteCeleb">
      <soap:operation soapAction="http://tempuri.org/DeleteCeleb" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetMovies">
      <soap:operation soapAction="http://tempuri.org/GetMovies" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AddWishlist">
      <soap:operation soapAction="http://tempuri.org/AddWishlist" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RemoveWishlist">
      <soap:operation soapAction="http://tempuri.org/RemoveWishlist" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RemoveFromWishList">
      <soap:operation soapAction="http://tempuri.org/RemoveFromWishList" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AddToCart">
      <soap:operation soapAction="http://tempuri.org/AddToCart" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="ServiceSoap12" type="tns:ServiceSoap">
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="Login">
      <soap12:operation soapAction="http://tempuri.org/Login" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Regi">
      <soap12:operation soapAction="http://tempuri.org/Regi" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="UpdateUser">
      <soap12:operation soapAction="http://tempuri.org/UpdateUser" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SearchUser">
      <soap12:operation soapAction="http://tempuri.org/SearchUser" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CreateMoviesTable">
      <soap12:operation soapAction="http://tempuri.org/CreateMoviesTable" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetAllMovies">
      <soap12:operation soapAction="http://tempuri.org/GetAllMovies" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetLatestMovies">
      <soap12:operation soapAction="http://tempuri.org/GetLatestMovies" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SearchMovies">
      <soap12:operation soapAction="http://tempuri.org/SearchMovies" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetWishlistMovies">
      <soap12:operation soapAction="http://tempuri.org/GetWishlistMovies" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AddToWishlist">
      <soap12:operation soapAction="http://tempuri.org/AddToWishlist" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RemoveFromWishlist">
      <soap12:operation soapAction="http://tempuri.org/RemoveFromWishlist" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AddWishListMovies">
      <soap12:operation soapAction="http://tempuri.org/AddWishListMovies" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AddMovieComment">
      <soap12:operation soapAction="http://tempuri.org/AddMovieComment" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetMovieComments">
      <soap12:operation soapAction="http://tempuri.org/GetMovieComments" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CreateCelebsTable">
      <soap12:operation soapAction="http://tempuri.org/CreateCelebsTable" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetAllCelebs">
      <soap12:operation soapAction="http://tempuri.org/GetAllCelebs" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetLatestCelebs">
      <soap12:operation soapAction="http://tempuri.org/GetLatestCelebs" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SearchCelebs">
      <soap12:operation soapAction="http://tempuri.org/SearchCelebs" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AddCeleb">
      <soap12:operation soapAction="http://tempuri.org/AddCeleb" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="UpdateCeleb">
      <soap12:operation soapAction="http://tempuri.org/UpdateCeleb" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="DeleteCeleb">
      <soap12:operation soapAction="http://tempuri.org/DeleteCeleb" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetMovies">
      <soap12:operation soapAction="http://tempuri.org/GetMovies" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AddWishlist">
      <soap12:operation soapAction="http://tempuri.org/AddWishlist" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RemoveWishlist">
      <soap12:operation soapAction="http://tempuri.org/RemoveWishlist" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RemoveFromWishList">
      <soap12:operation soapAction="http://tempuri.org/RemoveFromWishList" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AddToCart">
      <soap12:operation soapAction="http://tempuri.org/AddToCart" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Service">
    <wsdl:port name="ServiceSoap" binding="tns:ServiceSoap">
      <soap:address location="http://localhost:5790/Service.asmx" />
    </wsdl:port>
    <wsdl:port name="ServiceSoap12" binding="tns:ServiceSoap12">
      <soap12:address location="http://localhost:5790/Service.asmx" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>